### ISSUE TITLE
Setup / configure Heroku Deployment for  sedaily-event-stream kafka cluster

### ISSUE THREAD

**Issue by skabbass1** [SoftwareEngineeringDaily/sedaily-event-stream#2]
This  could wait until we have an MVC in place

**Comment by andrewmarklloyd** [comment]
We are currently deployed to an Amazon EC2 instance. Originally were waiting for Redis Streams to make it into the official release to be able to use the Redis Add-on for Heroku. According to [this update](http://antirez.com/news/116), Streams will not be released on the stable branch until the end of March. Along the way we moved towards making this API a direct input to InfluxDB for analytics. We should move forward with the deployment to Heroku since we aren't dependent on Redis at this time.

**Comment by andrewmarklloyd** [comment]
We are working this now. I have a staging environment setup at https://sedaily-devops-staging.herokuapp.com/

**Comment by andrewmarklloyd** [comment]
This is deployed to https://sedaily-devops.herokuapp.com now. @jasonify we can now remove the EC2 instance for the **API only**, not for the InfluxDB EC2 instance.
